name: uptime-kuma
services:
  uptime-kuma:
    container_name: uptime-kuma
    image: louislam/uptime-kuma:1
    restart: always
    ports:
      - ${IP:-127.0.0.1}:${PORT:-3001}:3001
    dns:
      - ${DNS1:-8.8.8.8}
      - ${DNS2:-8.8.4.4}
    volumes:
      - ./uptime-kuma:/app/data
